import pandas as pd
import numpy as np
import sklearn.impute as SimpleImputer
import matplotlib.pyplot as plt
import seaborn as sns
data = pd.read_csv('Datavisualization\\linechart.csv')
SRG_dept = data.groupby('department')['Sales Revenue Generated'].mean()

plt.figure(figsize=(8, 6))
SRG_dept.plot(kind='line',marker='o')
plt.title('Average sales revenue generated by Employees')
plt.xlabel('Churned')
plt.ylabel('Mean sales revenue')
plt.show()